<%@ Page Language="C#" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="admin_shipping.aspx.cs" Inherits="Admin_admin_shipping" Title="Shipping Calculator Admin" Culture="auto" meta:resourcekey="PageResource1" UICulture="auto" %>
<asp:Content ID="Content1" ContentPlaceHolderID="AdminPlaceHolder" Runat="Server">
<div id="centercontent">
    <h1>
        <asp:Localize ID="ShippingCalculatorContent" runat="server" meta:resourcekey="ShippingCalculatorContentResource1" Text="Shipping Calculator"></asp:Localize></h1>
    <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="shippingRateID"
        DataSourceID="SqlDataSource1" meta:resourcekey="GridView1Resource1">
        <Columns>
            <asp:BoundField DataField="Service" HeaderText="Service" SortExpression="Service" meta:resourcekey="BoundFieldResource1" />
            <asp:BoundField DataField="AmountPerUnit" HeaderText="Rate/Unit" SortExpression="AmountPerUnit" meta:resourcekey="BoundFieldResource2" />
        </Columns>
    </asp:GridView>
    <br />
    <h1>
        <asp:Localize ID="AddShippingRateContent" runat="server" meta:resourcekey="AddShippingRateContentResource1" Text="Add Shipping Rate"></asp:Localize></h1><br />
    <asp:FormView ID="FormView1" runat="server" DataKeyNames="shippingRateID" DataSourceID="SqlDataSource1"
        DefaultMode="Insert" meta:resourcekey="FormView1Resource1">
         <InsertItemTemplate>
             <asp:Localize ID="ServiceContent" runat="server" meta:resourcekey="ServiceContentResource1" Text="Service"></asp:Localize><br />
            <asp:TextBox ID="ServiceTextBox" runat="server" Text='<%# Bind("Service") %>' meta:resourcekey="ServiceTextBoxResource1"></asp:TextBox><br />
             <asp:Localize ID="AmountPerUnitContent" runat="server" meta:resourcekey="AmountPerUnitContentResource1" Text="Amount Per Unit"></asp:Localize><br />
            <asp:TextBox ID="DollarsPerPoundTextBox" runat="server" Text='<%# Bind("AmountPerUnit") %>' meta:resourcekey="DollarsPerPoundTextBoxResource1"></asp:TextBox><br /><br />
            <asp:LinkButton ID="InsertButton" runat="server" CommandName="Insert"
                Text="Insert" meta:resourcekey="InsertButtonResource1"></asp:LinkButton>
        </InsertItemTemplate>
    </asp:FormView>
    <br />
    <br />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceTemplate %>"
        DeleteCommand="DELETE FROM [CSK_Shipping_Rate] WHERE [shippingRateID] = @shippingRateID"
        InsertCommand="INSERT INTO [CSK_Shipping_Rate] ([Service], [AmountPerUnit]) VALUES (@Service, @AmountPerUnit)"
        SelectCommand="SELECT [shippingRateID], [Service], [AmountPerUnit] FROM [CSK_Shipping_Rate]"
        UpdateCommand="UPDATE [CSK_Shipping_Rate] SET [Service] = @Service, [AmountPerUnit] = @AmountPerUnit WHERE [shippingRateID] = @shippingRateID">
        <DeleteParameters>
            <asp:Parameter Name="shippingRateID" Type="Int32" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="Service" Type="String" />
            <asp:Parameter Name="AmountPerUnit" Type="Decimal" />
            <asp:Parameter Name="original_shippingRateID" Type="Int32" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="Service" Type="String" />
            <asp:Parameter Name="AmountPerUnit" Type="Decimal" />
        </InsertParameters>
    </asp:SqlDataSource>

</div>

</asp:Content>

