<%@ Page Language="C#" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="ShippingConfiguration.aspx.cs" Inherits="Admin_ShippingConfiguration" Title="Untitled Page" Culture="auto" meta:resourcekey="PageResource1" UICulture="auto" %>

<%@ Register Src="../Modules/ResultMessage.ascx" TagName="ResultMessage" TagPrefix="uc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="AdminPlaceHolder" Runat="Server">
   <atlas:UpdateProgress ID="uProgress" runat="server">
        <ProgressTemplate>
        <div class="loadingbox">
            <img src="../images/spinner.gif" align="absmiddle"/>&nbsp;&nbsp;<asp:Localize ID="ProcessingContent"
                runat="server" meta:resourcekey="ProcessingContentResource1" Text="Processing"></asp:Localize>...
        </div>
        </ProgressTemplate>
     </atlas:UpdateProgress> 
<atlas:UpdatePanel ID="WizUpdatePanel" runat="server" Mode="Conditional" >
<ContentTemplate>    




    <h1>
        <asp:Localize ID="ServicesContent" runat="server" meta:resourcekey="ServicesContentResource1" Text="Services"></asp:Localize></h1>
    <div class="sectionheader">
        <asp:Localize ID="SimpleShippingContent" runat="server" meta:resourcekey="SimpleShippingContentResource1" Text="Simple Shipping"></asp:Localize></div>
    <div class="sectionoutline">
    <div>
       <br />
        <asp:CheckBox ID="chkUseSimple" runat="server" Text="Use Simple Shipping" meta:resourcekey="chkUseSimpleResource1"/>
        <div class="tenpixspacer" />
    </div>
    <div>
        <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False"
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="shippingRateID"
            DataSourceID="SqlDataSource1" meta:resourcekey="GridView1Resource1">
            <Columns>
                <asp:BoundField DataField="Service" HeaderText="Servicio" SortExpression="Service" meta:resourcekey="BoundFieldResource1" />
                <asp:BoundField DataField="AmountPerUnit" HeaderText="Tasa/Unidad" SortExpression="AmountPerUnit" meta:resourcekey="BoundFieldResource2" />
            </Columns>
        </asp:GridView>
        <asp:FormView ID="FormView1" runat="server" DataKeyNames="shippingRateID" DataSourceID="SqlDataSource1"
            DefaultMode="Insert" meta:resourcekey="FormView1Resource1">
            <InsertItemTemplate>
                <asp:Localize ID="ServiceContent" runat="server" meta:resourcekey="ServiceContentResource1" Text="Service"></asp:Localize><br />
                <asp:TextBox ID="ServiceTextBox" runat="server" Text='<%# Bind("Service") %>' meta:resourcekey="ServiceTextBoxResource1"></asp:TextBox><br />
                <asp:Localize ID="AmountPerUnitContent" runat="server" meta:resourcekey="AmountPerUnitContentResource1" Text="Amount Per Unit"></asp:Localize><br />
                <asp:TextBox ID="DollarsPerPoundTextBox" runat="server" Text='<%# Bind("AmountPerUnit") %>' meta:resourcekey="DollarsPerPoundTextBoxResource1"></asp:TextBox><br />
                <br />
                <asp:LinkButton ID="InsertButton" runat="server" CommandName="Insert"
                    Text="Insert" meta:resourcekey="InsertButtonResource1"></asp:LinkButton>
            </InsertItemTemplate>
        </asp:FormView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CommerceTemplate %>"
            DeleteCommand="DELETE FROM [CSK_Shipping_Rate] WHERE [shippingRateID] = @shippingRateID"
            InsertCommand="INSERT INTO [CSK_Shipping_Rate] ([Service], [AmountPerUnit]) VALUES (@Service, @AmountPerUnit)"
            SelectCommand="SELECT [shippingRateID], [Service], [AmountPerUnit] FROM [CSK_Shipping_Rate]"
            UpdateCommand="UPDATE [CSK_Shipping_Rate] SET [Service] = @Service, [AmountPerUnit] = @AmountPerUnit WHERE [shippingRateID] = @shippingRateID">
            <DeleteParameters>
                <asp:Parameter Name="shippingRateID" Type="Int32" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="Service" Type="String" />
                <asp:Parameter Name="AmountPerUnit" Type="Decimal" />
                <asp:Parameter Name="original_shippingRateID" Type="Int32" />
            </UpdateParameters>
            <InsertParameters>
                <asp:Parameter Name="Service" Type="String" />
                <asp:Parameter Name="AmountPerUnit" Type="Decimal" />
            </InsertParameters>
        </asp:SqlDataSource>
    </div>
    </div>



</ContentTemplate>
</atlas:UpdatePanel>
</asp:Content>

