-- UPDATE A CSK_Store_Image
SET IDENTITY_INSERT [dbo].[CSK_Store_Image] ON

IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 2)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (2, 2, 'images/productimages/Bases de Datos/SQL Server/Sql2005Devs.jpg', 0, N'', '20060924', N'admin', '20060924', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 2, [imageFile] = 'images/productimages/Bases de Datos/SQL Server/Sql2005Devs.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20060924', [createdBy] = N'admin', [modifiedOn] = '20060924', [modifiedBy] = N'admin' WHERE [imageID] = 2


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 3)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (3, 3, 'images/productimages/Herramientas de Desarrollo/Visual Studio/WinAppsVs2005.jpg', 0, N'', '20060924', N'admin', '20060924', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 3, [imageFile] = 'images/productimages/Herramientas de Desarrollo/Visual Studio/WinAppsVs2005.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20060924', [createdBy] = N'admin', [modifiedOn] = '20060924', [modifiedBy] = N'admin' WHERE [imageID] = 3


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 4)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (4, 4, 'images/productimages/Herramientas de Desarrollo/Visual Studio/WebAppsVs2005.jpg', 0, N'', '20060924', N'admin', '20060924', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 4, [imageFile] = 'images/productimages/Herramientas de Desarrollo/Visual Studio/WebAppsVs2005.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20060924', [createdBy] = N'admin', [modifiedOn] = '20060924', [modifiedBy] = N'admin' WHERE [imageID] = 4


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 5)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (5, 5, 'images/productimages/Herramientas de Desarrollo/Visual Studio/WinAppsVs2005.jpg', 1, N'', '20061004', N'admin', '20061004', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 5, [imageFile] = 'images/productimages/Herramientas de Desarrollo/Visual Studio/WinAppsVs2005.jpg', [listOrder] = 1, [caption] = N'', [createdOn] = '20061004', [createdBy] = N'admin', [modifiedOn] = '20061004', [modifiedBy] = N'admin' WHERE [imageID] = 5


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 6)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (6, 6, 'images/productimages/Sistemas Operativos/Windows/CursoOptimizacionXpPeq.jpg', 1, N'', '20061004', N'admin', '20061004', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 6, [imageFile] = 'images/productimages/Sistemas Operativos/Windows/CursoOptimizacionXpPeq.jpg', [listOrder] = 1, [caption] = N'', [createdOn] = '20061004', [createdBy] = N'admin', [modifiedOn] = '20061004', [modifiedBy] = N'admin' WHERE [imageID] = 6


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 9)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (9, 1, 'images/productimages/Herramientas de Desarrollo/Visual Studio/IntroNetVb2005.jpg', 0, N'', '20060924', N'admin', '20060924', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 1, [imageFile] = 'images/productimages/Herramientas de Desarrollo/Visual Studio/IntroNetVb2005.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20060924', [createdBy] = N'admin', [modifiedOn] = '20060924', [modifiedBy] = N'admin' WHERE [imageID] = 9


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 10)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (10, 10, 'images/productimages/Utilitarios/Office/Office2007ProBox.jpg', 0, N'', '20060924', N'admin', '20060924', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 10, [imageFile] = 'images/productimages/Utilitarios/Office/Office2007ProBox.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20060924', [createdBy] = N'admin', [modifiedOn] = '20060924', [modifiedBy] = N'admin' WHERE [imageID] = 10


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 11)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (11, 11, 'images/productimages/Utilitarios/Office/Office2007StdBox.jpg', 0, N'', '20060924', N'admin', '20060924', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 11, [imageFile] = 'images/productimages/Utilitarios/Office/Office2007StdBox.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20060924', [createdBy] = N'admin', [modifiedOn] = '20060924', [modifiedBy] = N'admin' WHERE [imageID] = 11


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 12)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (12, 12, 'images/productimages/Bases de Datos/Oracle/Oracle10gSQL.jpg', 0, N'', '20060924', N'admin', '20060924', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 12, [imageFile] = 'images/productimages/Bases de Datos/Oracle/Oracle10gSQL.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20060924', [createdBy] = N'admin', [modifiedOn] = '20060924', [modifiedBy] = N'admin' WHERE [imageID] = 12


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 13)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (13, 14, 'images/productimages/Herramientas de Desarrollo/Java Studio Creator/JScript.jpg', 0, N'', '20061121', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 14, [imageFile] = 'images/productimages/Herramientas de Desarrollo/Java Studio Creator/JScript.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20061121', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [imageID] = 13


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 14)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (14, 15, 'images/productimages/Herramientas de Desarrollo/Java Studio Creator/AplicWebTomMySql.jpg', 0, N'', '20061121', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 15, [imageFile] = 'images/productimages/Herramientas de Desarrollo/Java Studio Creator/AplicWebTomMySql.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20061121', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [imageID] = 14


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 15)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (15, 16, 'images/productimages/Herramientas de Desarrollo/Java Studio Creator/IntroMundoJava.jpg', 0, N'', '20061121', N'admin', '20061121', NULL)
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 16, [imageFile] = 'images/productimages/Herramientas de Desarrollo/Java Studio Creator/IntroMundoJava.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20061121', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = NULL WHERE [imageID] = 15


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 16)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (16, 17, 'images/productimages/Sistemas Operativos/Linux/LinuxBasico.jpg', 0, N'', '20061121', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 17, [imageFile] = 'images/productimages/Sistemas Operativos/Linux/LinuxBasico.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20061121', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [imageID] = 16


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 17)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (17, 18, 'images/productimages/Sistemas Operativos/Linux/LinuxServer.jpg', 0, N'', '20061121', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 18, [imageFile] = 'images/productimages/Sistemas Operativos/Linux/LinuxServer.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20061121', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [imageID] = 17


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 18)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (18, 19, 'images/productimages/Sistemas Operativos/Linux/RedLinux.jpg', 0, N'', '20061121', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 19, [imageFile] = 'images/productimages/Sistemas Operativos/Linux/RedLinux.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20061121', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [imageID] = 18


IF NOT EXISTS (SELECT [imageID] FROM [dbo].[CSK_Store_Image] WHERE [imageID] = 19)
     INSERT INTO [dbo].[CSK_Store_Image] ([imageID], [productID], [imageFile], [listOrder], [caption], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (19, 20, 'images/productimages/Utilitarios/OpenOffice/OpenOffice.jpg', 0, N'', '20061122', N'admin', '20061122', NULL)
ELSE
     UPDATE [dbo].[CSK_Store_Image] SET [productID] = 20, [imageFile] = 'images/productimages/Utilitarios/OpenOffice/OpenOffice.jpg', [listOrder] = 0, [caption] = N'', [createdOn] = '20061122', [createdBy] = N'admin', [modifiedOn] = '20061122', [modifiedBy] = NULL WHERE [imageID] = 19


SET IDENTITY_INSERT [dbo].[CSK_Store_Image] OFF



-- UPDATE A CSK_Store_Product
SET IDENTITY_INSERT [dbo].[CSK_Store_Product] ON

IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 1)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (1, N'00003', N'Introducción a la Plataforma .NET con Visual Basic 2005', N'Este curso el provee a los estudiantes del conocimiento y las habilidades necesarias para desarrollar aplicaciones en Microsoft Visual Basic 2005 para la plataforma Microsoft .NET. El curso se enfoca en interfaces de usuario, estructura del programa, sintaxis del lenguaje y detalles de implementación. Este es el primer curso en el currículo de Visual Basic 2005 y servirá como punto de entrada para otros cursos de .NET.', 1, N'', 1, 3, 1, 1, 1, N'Guayaquil', 13.0000, 18.0000, 2.0000, 'USD', N'unidad', N'', 3, 2, 3, 'centímetro', 0, 3, 4, 1, N'images/productimages/Herramientas de Desarrollo/Visual Studio/IntroNetVb2005.jpg', '20060924', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00003', [productName] = N'Introducción a la Plataforma .NET con Visual Basic 2005', [shortDescription] = N'Este curso el provee a los estudiantes del conocimiento y las habilidades necesarias para desarrollar aplicaciones en Microsoft Visual Basic 2005 para la plataforma Microsoft .NET. El curso se enfoca en interfaces de usuario, estructura del programa, sintaxis del lenguaje y detalles de implementación. Este es el primer curso en el currículo de Visual Basic 2005 y servirá como punto de entrada para otros cursos de .NET.', [manufacturerID] = 1, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 3, [shippingTypeID] = 1, [shipEstimateID] = 1, [taxTypeID] = 1, [stockLocation] = N'Guayaquil', [ourPrice] = 13.0000, [retailPrice] = 18.0000, [weight] = 2.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'unidad', [adminComments] = N'', [length] = 3, [height] = 2, [width] = 3, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 3, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Herramientas de Desarrollo/Visual Studio/IntroNetVb2005.jpg', [createdOn] = '20060924', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 1


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 2)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (2, N'00004', N'SQL Server 2005 para Desarrolladores', N'Este curso tiene como objetivo dar a los participantes una introducción rápida al nuevo mundo del desarrollo de bases de datos con SQL Server 2005. El material cubre el manejo del nuevo entorno integrado de herramientas para desarrollador para implementar una base de datos. Se fundamentará los conceptos y principios básicos como creación Tablas, Claves, Claves Foráneas, Vistas, Queries y Procedimientos Almacenados.', 1, N'', 1, 3, 1, 1, 1, N'Guayaquil', 13.0000, 19.0000, 2.0000, 'USD', N'Unidad', N'', 3, 1, 2, 'centímetro', 0, 4, 4, 1, N'images/productimages/Bases de Datos/SQL Server/Sql2005Devs.jpg', '20060924', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00004', [productName] = N'SQL Server 2005 para Desarrolladores', [shortDescription] = N'Este curso tiene como objetivo dar a los participantes una introducción rápida al nuevo mundo del desarrollo de bases de datos con SQL Server 2005. El material cubre el manejo del nuevo entorno integrado de herramientas para desarrollador para implementar una base de datos. Se fundamentará los conceptos y principios básicos como creación Tablas, Claves, Claves Foráneas, Vistas, Queries y Procedimientos Almacenados.', [manufacturerID] = 1, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 3, [shippingTypeID] = 1, [shipEstimateID] = 1, [taxTypeID] = 1, [stockLocation] = N'Guayaquil', [ourPrice] = 13.0000, [retailPrice] = 19.0000, [weight] = 2.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'Unidad', [adminComments] = N'', [length] = 3, [height] = 1, [width] = 2, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 4, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Bases de Datos/SQL Server/Sql2005Devs.jpg', [createdOn] = '20060924', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 2


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 3)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (3, N'00001', N'Desarrollo de Aplicaciones Windows con Visual Studio 2005', N'Este curso provee a los estudiantes el conocimiento y las habilidades para desarrollar aplicaciones Windows utilizando Visual Studio 2005. El curso se enfoca en interfaces de usuario, estructura del programa y detalles de implementación. El curso incluye código de ejemplo tanto en Visual Basic 2005 como en Visual C# 2005.', 1, N'', 1, 3, 1, 1, 1, N'Guayaquil, Ecuador', 13.0000, 20.0000, 2.0000, 'USD', N'unidad', N'', 1, 5, 2, 'centímetro', 0, 1, 4, 1, N'images/productimages/Herramientas de Desarrollo/Visual Studio/WinAppsVs2005.jpg', '20060919', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00001', [productName] = N'Desarrollo de Aplicaciones Windows con Visual Studio 2005', [shortDescription] = N'Este curso provee a los estudiantes el conocimiento y las habilidades para desarrollar aplicaciones Windows utilizando Visual Studio 2005. El curso se enfoca en interfaces de usuario, estructura del programa y detalles de implementación. El curso incluye código de ejemplo tanto en Visual Basic 2005 como en Visual C# 2005.', [manufacturerID] = 1, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 3, [shippingTypeID] = 1, [shipEstimateID] = 1, [taxTypeID] = 1, [stockLocation] = N'Guayaquil, Ecuador', [ourPrice] = 13.0000, [retailPrice] = 20.0000, [weight] = 2.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'unidad', [adminComments] = N'', [length] = 1, [height] = 5, [width] = 2, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 1, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Herramientas de Desarrollo/Visual Studio/WinAppsVs2005.jpg', [createdOn] = '20060919', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 3


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 4)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (4, N'00002', N'Desarrollo de Aplicaciones Web con Visual Studio 2005', N'Este curso provee a los estudiantes el conocimiento y las habilidades para desarrollar aplicaciones Web ASP.NE 2.0 utilizando Visual Studio 2005. El curso se enfoca en interfaces de usuario, estructura y funcionalidad del sitio Web y detalles de implementación. El curso incluye código de ejemplo tanto en Visual Basic 2005 como en Visual C# 2005.', 1, N'', 1, 3, 1, 1, 1, N'Guayaquil', 13.0000, 20.0000, 3.0000, 'USD', N'unidad', N'', 3, 2, 3, 'centímetro', 0, 2, 4, 1, N'images/productimages/Herramientas de Desarrollo/Visual Studio/WebAppsVs2005.jpg', '20060924', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00002', [productName] = N'Desarrollo de Aplicaciones Web con Visual Studio 2005', [shortDescription] = N'Este curso provee a los estudiantes el conocimiento y las habilidades para desarrollar aplicaciones Web ASP.NE 2.0 utilizando Visual Studio 2005. El curso se enfoca en interfaces de usuario, estructura y funcionalidad del sitio Web y detalles de implementación. El curso incluye código de ejemplo tanto en Visual Basic 2005 como en Visual C# 2005.', [manufacturerID] = 1, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 3, [shippingTypeID] = 1, [shipEstimateID] = 1, [taxTypeID] = 1, [stockLocation] = N'Guayaquil', [ourPrice] = 13.0000, [retailPrice] = 20.0000, [weight] = 3.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'unidad', [adminComments] = N'', [length] = 3, [height] = 2, [width] = 3, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 2, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Herramientas de Desarrollo/Visual Studio/WebAppsVs2005.jpg', [createdOn] = '20060924', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 4


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 5)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (5, N'00005', N'Desarrollo de Aplicaciones Windows con Visual Studio 2005 (Digital)', N'Este curso provee a los estudiantes el conocimiento y las habilidades para desarrollar aplicaciones Windows utilizando Visual Studio 2005. El curso se enfoca en interfaces de usuario, estructura del programa y detalles de implementación. El curso incluye código de ejemplo tanto en Visual Basic 2005 como en Visual C# 2005.', 1, N'', 1, 1, 3, 1, 2, N'Guayaquil, Ecuador', 13.0000, 20.0000, 2.0000, 'USD', N'unidad', N'', 1, 5, 2, 'centímetro', 0, 5, 4, 1, N'images/productimages/Herramientas de Desarrollo/Visual Studio/WinAppsVs2005.jpg', '20061004', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00005', [productName] = N'Desarrollo de Aplicaciones Windows con Visual Studio 2005 (Digital)', [shortDescription] = N'Este curso provee a los estudiantes el conocimiento y las habilidades para desarrollar aplicaciones Windows utilizando Visual Studio 2005. El curso se enfoca en interfaces de usuario, estructura del programa y detalles de implementación. El curso incluye código de ejemplo tanto en Visual Basic 2005 como en Visual C# 2005.', [manufacturerID] = 1, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 1, [shippingTypeID] = 3, [shipEstimateID] = 1, [taxTypeID] = 2, [stockLocation] = N'Guayaquil, Ecuador', [ourPrice] = 13.0000, [retailPrice] = 20.0000, [weight] = 2.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'unidad', [adminComments] = N'', [length] = 1, [height] = 5, [width] = 2, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 5, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Herramientas de Desarrollo/Visual Studio/WinAppsVs2005.jpg', [createdOn] = '20061004', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 5


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 6)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (6, N'00006', N'Optimice su PC con XP (Digital)', N'Usted puede optimizar el rendimiento de su computadora solo con modificar ciertas configuraciones de su sistema operativo. Si pone en práctica los concejos que contiene esta guía, Usted conseguirá que Windows y sus aplicaciones aceleren el arranque y aprovechen mejor los recursos de su PC.', 2, N'', 1, 1, 3, 1, 2, N'Guayaquil, Ecuador', 13.0000, 15.0000, 2.0000, 'USD', N'unidad', N'', 2, 3, 1, 'centímetro', 0, 6, 4, 1, N'images/productimages/Sistemas Operativos/Windows/CursoOptimizacionXpPeq.jpg', '20061004', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00006', [productName] = N'Optimice su PC con XP (Digital)', [shortDescription] = N'Usted puede optimizar el rendimiento de su computadora solo con modificar ciertas configuraciones de su sistema operativo. Si pone en práctica los concejos que contiene esta guía, Usted conseguirá que Windows y sus aplicaciones aceleren el arranque y aprovechen mejor los recursos de su PC.', [manufacturerID] = 2, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 1, [shippingTypeID] = 3, [shipEstimateID] = 1, [taxTypeID] = 2, [stockLocation] = N'Guayaquil, Ecuador', [ourPrice] = 13.0000, [retailPrice] = 15.0000, [weight] = 2.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'unidad', [adminComments] = N'', [length] = 2, [height] = 3, [width] = 1, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 6, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Sistemas Operativos/Windows/CursoOptimizacionXpPeq.jpg', [createdOn] = '20061004', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 6


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 10)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (10, N'00007', N'Lo Nuevo de Excel 2007', N'Este curso presenta las nuevas características y funcionalidad de la última versión de Microsoft Office Excel. Ha habido substanciales cambios a la interfaz gráfica en esta aplicación de hoja de cálculo y este curso le ayudará a conocer rápidamente todas las nuevas funcionalidades. Este curso cubre las nuevas características que le permiten organizar y analizar información del negocio en Office Excel 2007.', 1, N'', 1, 4, 1, 1, 1, N'Guayaquil', 13.0000, 17.0000, 2.0000, 'USD', N'unidad', N'', 3, 2, 3, 'centímetro', 0, 7, 4, 1, N'images/productimages/Utilitarios/Office/Office2007ProBox.jpg', '20061105', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00007', [productName] = N'Lo Nuevo de Excel 2007', [shortDescription] = N'Este curso presenta las nuevas características y funcionalidad de la última versión de Microsoft Office Excel. Ha habido substanciales cambios a la interfaz gráfica en esta aplicación de hoja de cálculo y este curso le ayudará a conocer rápidamente todas las nuevas funcionalidades. Este curso cubre las nuevas características que le permiten organizar y analizar información del negocio en Office Excel 2007.', [manufacturerID] = 1, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 4, [shippingTypeID] = 1, [shipEstimateID] = 1, [taxTypeID] = 1, [stockLocation] = N'Guayaquil', [ourPrice] = 13.0000, [retailPrice] = 17.0000, [weight] = 2.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'unidad', [adminComments] = N'', [length] = 3, [height] = 2, [width] = 3, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 7, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Utilitarios/Office/Office2007ProBox.jpg', [createdOn] = '20061105', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 10


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 11)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (11, N'00008', N'Lo Nuevo de Word 2007', N'Este curso presenta las nuevas características y funcionalidad de la última versión de Microsoft Office Word. Ha habido substanciales cambios a la interfaz gráfica en esta aplicación de procesamiento de palabras y este curso le ayudará a conocer rápidamente todas las nuevas funcionalidades. Este curso cubre las nuevas características que le permiten crear documentos con apariencia profesional en Office Word.', 1, N'', 1, 4, 1, 1, 1, N'Guayaquil', 13.0000, 17.0000, 2.0000, 'USD', N'unidad', N'', 3, 2, 3, 'centímetro', 0, 8, 4, 1, N'images/productimages/Utilitarios/Office/Office2007StdBox.jpg', '20061105', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00008', [productName] = N'Lo Nuevo de Word 2007', [shortDescription] = N'Este curso presenta las nuevas características y funcionalidad de la última versión de Microsoft Office Word. Ha habido substanciales cambios a la interfaz gráfica en esta aplicación de procesamiento de palabras y este curso le ayudará a conocer rápidamente todas las nuevas funcionalidades. Este curso cubre las nuevas características que le permiten crear documentos con apariencia profesional en Office Word.', [manufacturerID] = 1, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 4, [shippingTypeID] = 1, [shipEstimateID] = 1, [taxTypeID] = 1, [stockLocation] = N'Guayaquil', [ourPrice] = 13.0000, [retailPrice] = 17.0000, [weight] = 2.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'unidad', [adminComments] = N'', [length] = 3, [height] = 2, [width] = 3, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 8, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Utilitarios/Office/Office2007StdBox.jpg', [createdOn] = '20061105', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 11


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 12)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (12, N'00009', N'Oracle Database 10g: Introducción a SQL (Digital)', N'Este curso presenta la tecnología de Oracle Database 20g y los conceptos de bases de datos relacionales y el poderoso lenguaje de programación SQL. Este curso provee al estudiante las habilidades SQL escenciales para consultar la base de datos, la meta data y la creación de objetos de base de datos. ', 3, N'', 1, 1, 3, 1, 2, N'Guayaquil', 13.0000, 20.0000, 2.0000, 'USD', N'unidad', N'', 3, 2, 3, 'centímetro', 0, 9, 4, 1, N'images/productimages/Bases de Datos/Oracle/Oracle10gSQL.jpg', '20061105', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00009', [productName] = N'Oracle Database 10g: Introducción a SQL (Digital)', [shortDescription] = N'Este curso presenta la tecnología de Oracle Database 20g y los conceptos de bases de datos relacionales y el poderoso lenguaje de programación SQL. Este curso provee al estudiante las habilidades SQL escenciales para consultar la base de datos, la meta data y la creación de objetos de base de datos. ', [manufacturerID] = 3, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 1, [shippingTypeID] = 3, [shipEstimateID] = 1, [taxTypeID] = 2, [stockLocation] = N'Guayaquil', [ourPrice] = 13.0000, [retailPrice] = 20.0000, [weight] = 2.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'unidad', [adminComments] = N'', [length] = 3, [height] = 2, [width] = 3, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 9, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Bases de Datos/Oracle/Oracle10gSQL.jpg', [createdOn] = '20061105', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 12


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 14)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (14, N'00011', N'Introducción a JavaScript', N'Manual de Referencia basado en el Lenguaje JavaScript compatible con los navegadores Explorer y Netscape.
Derechos Reservados : Jorge Sánchez (www.jorgesanchez.net)', 2, N'', 1, 1, 3, 1, 2, N'', 13.0000, 19.0000, 1.0000, 'USD', N'item', N'', 15, 1, 10, 'centímetro', 0, 99, 4, 1, N'images/productimages/Herramientas de Desarrollo/Java Studio Creator/JScript.jpg', '20061120', N'admin', '20061120', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00011', [productName] = N'Introducción a JavaScript', [shortDescription] = N'Manual de Referencia basado en el Lenguaje JavaScript compatible con los navegadores Explorer y Netscape.
Derechos Reservados : Jorge Sánchez (www.jorgesanchez.net)', [manufacturerID] = 2, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 1, [shippingTypeID] = 3, [shipEstimateID] = 1, [taxTypeID] = 2, [stockLocation] = N'', [ourPrice] = 13.0000, [retailPrice] = 19.0000, [weight] = 1.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'item', [adminComments] = N'', [length] = 15, [height] = 1, [width] = 10, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 99, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Herramientas de Desarrollo/Java Studio Creator/JScript.jpg', [createdOn] = '20061120', [createdBy] = N'admin', [modifiedOn] = '20061120', [modifiedBy] = N'admin' WHERE [productID] = 14


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 15)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (15, N'00012', N'Aplicación Web Real con Tomcat 4 y MySQL', N'Excelente curso, en el cuál tienes la opción de aprender Java, realizando una aplicación de ejemplo utilizando Tomcat y MySQL para crear aplicaciones web profesionales con acceso a BD con herramientas gratuitas. Esta es tú oportunidad.', 2, N'', 1, 1, 3, 1, 2, N'', 13.0000, 21.0000, 1.0000, 'USD', N'item', N'', 15, 1, 10, 'centímetro', 0, 99, 4, 1, N'images/productimages/Herramientas de Desarrollo/Java Studio Creator/AplicWebTomMySql.jpg', '20061120', N'admin', '20061120', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00012', [productName] = N'Aplicación Web Real con Tomcat 4 y MySQL', [shortDescription] = N'Excelente curso, en el cuál tienes la opción de aprender Java, realizando una aplicación de ejemplo utilizando Tomcat y MySQL para crear aplicaciones web profesionales con acceso a BD con herramientas gratuitas. Esta es tú oportunidad.', [manufacturerID] = 2, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 1, [shippingTypeID] = 3, [shipEstimateID] = 1, [taxTypeID] = 2, [stockLocation] = N'', [ourPrice] = 13.0000, [retailPrice] = 21.0000, [weight] = 1.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'item', [adminComments] = N'', [length] = 15, [height] = 1, [width] = 10, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 99, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Herramientas de Desarrollo/Java Studio Creator/AplicWebTomMySql.jpg', [createdOn] = '20061120', [createdBy] = N'admin', [modifiedOn] = '20061120', [modifiedBy] = N'admin' WHERE [productID] = 15


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 16)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (16, N'00013', N'Introducción al Mundo Java', N'Este curso es la introducción al Mundo Java. Fácil y sencillo con ejemplos prácticos y variados.', 2, N'', 1, 1, 3, 1, 2, N'', 13.0000, 15.0000, 1.0000, 'USD', N'item', N'', 15, 1, 10, 'centímetro', 0, 99, 4, 1, N'images/productimages/Herramientas de Desarrollo/Java Studio Creator/IntroMundoJava.jpg', '20061120', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00013', [productName] = N'Introducción al Mundo Java', [shortDescription] = N'Este curso es la introducción al Mundo Java. Fácil y sencillo con ejemplos prácticos y variados.', [manufacturerID] = 2, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 1, [shippingTypeID] = 3, [shipEstimateID] = 1, [taxTypeID] = 2, [stockLocation] = N'', [ourPrice] = 13.0000, [retailPrice] = 15.0000, [weight] = 1.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'item', [adminComments] = N'', [length] = 15, [height] = 1, [width] = 10, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 99, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Herramientas de Desarrollo/Java Studio Creator/IntroMundoJava.jpg', [createdOn] = '20061120', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 16


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 17)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (17, N'00014', N'Linux Básico', N'El objetivo de este curso será la de que obtengas los conocimientos adecuados para que a partir del primer día ya puedas disfrutar del potencial de Linux, que en una semana te pongas al día, y que en un mes seas un usuario que puedas recomendar algunas sugerencias a otros nuevos usuarios.', 2, N'', 1, 1, 1, 1, 2, N'', 13.0000, 20.0000, 1.0000, 'USD', N'item', N'', 15, 1, 10, 'centímetro', 0, 99, 4, 1, N'images/productimages/Sistemas Operativos/Linux/LinuxBasico.jpg', '20061121', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00014', [productName] = N'Linux Básico', [shortDescription] = N'El objetivo de este curso será la de que obtengas los conocimientos adecuados para que a partir del primer día ya puedas disfrutar del potencial de Linux, que en una semana te pongas al día, y que en un mes seas un usuario que puedas recomendar algunas sugerencias a otros nuevos usuarios.', [manufacturerID] = 2, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 1, [shippingTypeID] = 1, [shipEstimateID] = 1, [taxTypeID] = 2, [stockLocation] = N'', [ourPrice] = 13.0000, [retailPrice] = 20.0000, [weight] = 1.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'item', [adminComments] = N'', [length] = 15, [height] = 1, [width] = 10, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 99, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Sistemas Operativos/Linux/LinuxBasico.jpg', [createdOn] = '20061121', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 17


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 18)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (18, N'00015', N'Linux Server', N'Este curso te ayudará a conocer LINUX como un servicio de comunicación entre el hardware y el software de un sistema computacional.', 2, N'', 1, 1, 1, 1, 2, N'', 13.0000, 15.0000, 1.0000, 'USD', N'item', N'', 15, 1, 10, 'centímetro', 0, 99, 4, 1, N'images/productimages/Sistemas Operativos/Linux/LinuxServer.jpg', '20061121', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00015', [productName] = N'Linux Server', [shortDescription] = N'Este curso te ayudará a conocer LINUX como un servicio de comunicación entre el hardware y el software de un sistema computacional.', [manufacturerID] = 2, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 1, [shippingTypeID] = 1, [shipEstimateID] = 1, [taxTypeID] = 2, [stockLocation] = N'', [ourPrice] = 13.0000, [retailPrice] = 15.0000, [weight] = 1.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'item', [adminComments] = N'', [length] = 15, [height] = 1, [width] = 10, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 99, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Sistemas Operativos/Linux/LinuxServer.jpg', [createdOn] = '20061121', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 18


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 19)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (19, N'00016', N'Redes de Linux, cómo funcionan', N'Curso dedicado para entender la evolución de las capacidades de Linux para tratar con redes informáticas. Este curso es el punto de partida para aprender todo sobre el mantenimiento de redes TCP/IP, la configuración de los archivos relacionados con la red, y hay un amplio capítulo sobre configuración de dispositivos físicos.', 2, N'', 1, 1, 1, 1, 2, N'', 13.0000, 25.0000, 1.0000, 'USD', N'item', N'', 15, 1, 10, 'centímetro', 0, 99, 4, 1, N'images/productimages/Sistemas Operativos/Linux/RedLinux.jpg', '20061121', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00016', [productName] = N'Redes de Linux, cómo funcionan', [shortDescription] = N'Curso dedicado para entender la evolución de las capacidades de Linux para tratar con redes informáticas. Este curso es el punto de partida para aprender todo sobre el mantenimiento de redes TCP/IP, la configuración de los archivos relacionados con la red, y hay un amplio capítulo sobre configuración de dispositivos físicos.', [manufacturerID] = 2, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 1, [shippingTypeID] = 1, [shipEstimateID] = 1, [taxTypeID] = 2, [stockLocation] = N'', [ourPrice] = 13.0000, [retailPrice] = 25.0000, [weight] = 1.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'item', [adminComments] = N'', [length] = 15, [height] = 1, [width] = 10, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 99, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Sistemas Operativos/Linux/RedLinux.jpg', [createdOn] = '20061121', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 19


IF NOT EXISTS (SELECT [productID] FROM [dbo].[CSK_Store_Product] WHERE [productID] = 20)
     INSERT INTO [dbo].[CSK_Store_Product] ([productID], [sku], [productName], [shortDescription], [manufacturerID], [attributeXML], [statusID], [productTypeID], [shippingTypeID], [shipEstimateID], [taxTypeID], [stockLocation], [ourPrice], [retailPrice], [weight], [currencyCode], [unitOfMeasure], [adminComments], [length], [height], [width], [dimensionUnit], [isDeleted], [listOrder], [ratingSum], [totalRatingVotes], [defaultImage], [createdOn], [createdBy], [modifiedOn], [modifiedBy])
     VALUES (20, N'00017', N'OpenOffice.org', N'Este curso te ayudará a responder la pregunta ¿Qué es OpenOffice.org?, con el cuál conocerás lo referente de código fuente libre basado en la suite StarOffice de Sun Microsystems con versiones para todos los sistemas operativos importantes. ', 2, N'', 1, 1, 1, 1, 2, N'', 13.0000, 18.0000, 1.0000, 'USD', N'item', N'', 15, 1, 10, 'centímetro', 0, 99, 4, 1, N'images/productimages/Utilitarios/OpenOffice/OpenOffice.jpg', '20061121', N'admin', '20061121', N'admin')
ELSE
     UPDATE [dbo].[CSK_Store_Product] SET [sku] = N'00017', [productName] = N'OpenOffice.org', [shortDescription] = N'Este curso te ayudará a responder la pregunta ¿Qué es OpenOffice.org?, con el cuál conocerás lo referente de código fuente libre basado en la suite StarOffice de Sun Microsystems con versiones para todos los sistemas operativos importantes. ', [manufacturerID] = 2, [attributeXML] = N'', [statusID] = 1, [productTypeID] = 1, [shippingTypeID] = 1, [shipEstimateID] = 1, [taxTypeID] = 2, [stockLocation] = N'', [ourPrice] = 13.0000, [retailPrice] = 18.0000, [weight] = 1.0000, [currencyCode] = 'USD', [unitOfMeasure] = N'item', [adminComments] = N'', [length] = 15, [height] = 1, [width] = 10, [dimensionUnit] = 'centímetro', [isDeleted] = 0, [listOrder] = 99, [ratingSum] = 4, [totalRatingVotes] = 1, [defaultImage] = N'images/productimages/Utilitarios/OpenOffice/OpenOffice.jpg', [createdOn] = '20061121', [createdBy] = N'admin', [modifiedOn] = '20061121', [modifiedBy] = N'admin' WHERE [productID] = 20


SET IDENTITY_INSERT [dbo].[CSK_Store_Product] OFF