//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.308
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commerce.Providers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commerce.Providers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge amount cannot be 0 or less.
        /// </summary>
        internal static string AmountCannotBeZero {
            get {
                return ResourceManager.GetString("AmountCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load default PaymentProvider.
        /// </summary>
        internal static string CannotLoadDefaultPaymentProvider {
            get {
                return ResourceManager.GetString("CannotLoadDefaultPaymentProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load PFX for call to PayPal. The file cannot be found at .
        /// </summary>
        internal static string CannotLoadPFX {
            get {
                return ResourceManager.GetString("CannotLoadPFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Merchant ID value.
        /// </summary>
        internal static string EmptyMerchantID {
            get {
                return ResourceManager.GetString("EmptyMerchantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Paypal Service Password value.
        /// </summary>
        internal static string EmptyPaypalPassword {
            get {
                return ResourceManager.GetString("EmptyPaypalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Paypal Service Username value.
        /// </summary>
        internal static string EmptyPaypalUsername {
            get {
                return ResourceManager.GetString("EmptyPaypalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty SSL Cert File value.
        /// </summary>
        internal static string EmptySSLCertFile {
            get {
                return ResourceManager.GetString("EmptySSLCertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty SSL Cert Location value.
        /// </summary>
        internal static string EmptySSLCertLocation {
            get {
                return ResourceManager.GetString("EmptySSLCertLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty SSL Cert Password value.
        /// </summary>
        internal static string EmptySSLCertPassword {
            get {
                return ResourceManager.GetString("EmptySSLCertPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This credit card appears to be expired.
        /// </summary>
        internal static string ExpiredCreditCard {
            get {
                return ResourceManager.GetString("ExpiredCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credit Card Number.
        /// </summary>
        internal static string InvalidCreditCardNumber {
            get {
                return ResourceManager.GetString("InvalidCreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid provider type.
        /// </summary>
        internal static string InvalidProvider {
            get {
                return ResourceManager.GetString("InvalidProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order has no existing transactions; please be sure the transactions are loaded for this order. Cannot refund.
        /// </summary>
        internal static string OrderWithNoTransactions {
            get {
                return ResourceManager.GetString("OrderWithNoTransactions", resourceCulture);
            }
        }
    }
}
