<%@ Page Language="C#" AutoEventWireup="true" CodeFile="TermsConditions.aspx.cs" Inherits="TermsConditions" Title="T&eacute;rminos y Condiciones de Venta" %>
<head id="Head1" runat="server" />
    <h1>
        <span style="font-size: 14pt">T&eacute;rminos y Condiciones de Venta</span>
    </h1>
<ol type="1">
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Definiciones</strong>. &nbsp; </span></li>
</ol>
<div style="MARGIN: 0cm 0cm 10pt 36pt; LINE-HEIGHT: normal"><strong><span style="FONT-SIZE: 12pt">&quot;Ud&quot; o &quot;Cliente&quot;</span></strong><span style="FONT-SIZE: 12pt"> persona f&iacute;sica o jur&iacute;dica que compra o usa los Cursos. </span></div>
<div style="MARGIN: 0cm 0cm 10pt 36pt; LINE-HEIGHT: normal"><strong><span style="FONT-SIZE: 12pt">&quot;Consumidor&quot;</span></strong><span style="FONT-SIZE: 12pt"> persona f&iacute;sica o jur&iacute;dica que adquiere los Cursos para su propio uso o el de su grupo familiar o social.</span></div>
<div style="MARGIN: 0cm 0cm 10pt 36pt; LINE-HEIGHT: normal"><strong><span style="FONT-SIZE: 12pt">&quot;Latino E-Learning&quot; o &quot;nosotros&quot;</span></strong><span style="FONT-SIZE: 12pt"> Latino E-Learning o cuyo nombre aparezca en la factura, domiciliadas en la direcci&oacute;n que se indica en la factura y, cuando corresponda, el Proveedor de Servicios.</span></div>
<div style="MARGIN: 0cm 0cm 10pt 36pt; LINE-HEIGHT: normal"><strong><span style="FONT-SIZE: 12pt">&quot;Confirmaci&oacute;n del Pedido&quot;</span></strong><span style="FONT-SIZE: 12pt"> documento o acto por el que&nbsp;acepta un pedido de los Cursos.</span></div>
<div style="MARGIN: 0cm 0cm 10pt 36pt; LINE-HEIGHT: normal"><strong><span style="FONT-SIZE: 12pt">&quot;Precio&quot;</span></strong><span style="FONT-SIZE: 12pt"> precio indicado en la Confirmaci&oacute;n del Pedido.</span></div>
<div style="MARGIN: 0cm 0cm 10pt 36pt; LINE-HEIGHT: normal"><strong><span style="FONT-SIZE: 12pt">&quot;Curso&quot;</span></strong><span style="FONT-SIZE: 12pt"> bien descrito en la Confirmaci&oacute;n del Pedido.</span></div>
<div style="MARGIN: 0cm 0cm 10pt 36pt; LINE-HEIGHT: normal"><strong><span style="FONT-SIZE: 12pt">&quot;Software&quot; </span></strong><span style="FONT-SIZE: 12pt">programas de computaci&oacute;n, entre ellos sistemas operativos o aplicaciones inform&aacute;ticas. </span></div>
<ol type="1" start="2">
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>&Aacute;mbito de Aplicaci&oacute;n</strong>.&nbsp; Estos T&eacute;rminos y Condiciones Generales de Venta son aplicables a cualesquier y todas las compraventas y/o servicios descritos, mencionados, promocionados o incluidos en cualquiera de sus formas, en nuestros folletos, promociones, listas de precios, anuncios, presupuestos, y propuestas de Latino E-Learning, por Internet o verbalmente. Se excluyen cualesquiera otros t&eacute;rminos o condiciones que pudieran aplicarse. Al momento de realizar un pedido supone su aceptaci&oacute;n a los presentes T&eacute;rminos y Condiciones Generales de Venta. Latino E-Learning se reserva el derecho de modificar los T&eacute;rminos y Condiciones Generales en cualquier momento y, a partir de la fecha de modificaci&oacute;n, las nuevas operaciones que se celebren entre Latino E-Learning y sus Clientes se regir&aacute;n por el documento modificado. La aceptaci&oacute;n, por Latino E-Learning, de la orden de compra del Cliente no implica la aceptaci&oacute;n, por Latino E-Learning, de las cl&aacute;usulas y condiciones de tal orden de compra, independientemente de la forma en que est&eacute;n descriptas, entre las que cabe mencionar, por ejemplo, cl&aacute;usulas que no guarden coherencia y cl&aacute;usulas que se agreguen a las cl&aacute;usulas y condiciones de estos T&eacute;rminos y Condiciones Generales de Venta. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Pedido/Contrato</strong>.&nbsp; Los pedidos se aceptar&aacute;n por escrito, correo electr&oacute;nico, tel&eacute;fono o fax y s&oacute;lo ser&aacute;n vinculantes una vez aceptados por Latino E-Learning mediante la emisi&oacute;n de una Confirmaci&oacute;n del Pedido por cualquiera de los medios de comunicaci&oacute;n antes descritos. Ud. debe verificar la Confirmaci&oacute;n del Pedido y notificarnos, inmediatamente, por escrito, cualquier error. En caso contrario, la descripci&oacute;n del Curso en la Confirmaci&oacute;n del Pedido pasar&aacute; a integrar este contrato y ser&aacute; vinculatoria para las partes. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Precio y T&eacute;rminos de Pago</strong>.&nbsp; Los presupuestos y/u ofertas econ&oacute;micas, s&oacute;lo ser&aacute;n v&aacute;lidos por escrito y durante el plazo que cada uno indique. En caso de omisi&oacute;n de este dato, el plazo ser&aacute; de 30 d&iacute;as naturales. Latino E-Learning se reserva el derecho de suministrar Cursos diferentes a los solicitados en cualquier momento, pero garantizamos que el prop&oacute;sito para el que fue dise&ntilde;ado y el funcionamiento de cursos entregados ser&aacute;n equivalentes a las de los cursos solicitados. El Precio del Curso y los t&eacute;rminos y condiciones de pago se establecer&aacute;n en la Confirmaci&oacute;n del Pedido. El Precio excluye impuestos, gastos de env&iacute;o, seguro e instalaci&oacute;n, salvo se se&ntilde;ale expl&iacute;citamente lo contrario. Los tipos de cambio de divisa, aranceles, seguros y costos de producci&oacute;n (incluyendo los de componentes y servicios) pueden hacer que el precio final var&iacute;e y hacer que Latino E-Learning ajuste &eacute;stos. El pago deber&aacute; efectuarse al momento de realizar el pedido o en las condiciones que se establezcan en la Confirmaci&oacute;n de Pedido. Latino E-Learning puede suspender la entrega del Curso o la prestaci&oacute;n del servicio hasta su pago total. En caso de demora en el pago (mora), se cobrar&aacute;n los costos de recuperaci&oacute;n y se aplicar&aacute; un inter&eacute;s moratorio sobre la cantidad adeudada por cada d&iacute;a que dicha cantidad permanezca insoluta, a partir de la fecha de vencimiento de pago y hasta su pago total, a una tasa de inter&eacute;s anual igual a la tasa preferencial (&quot;Prime Rate&quot;) cotizada por la oficina en Nueva York, NY de Citibank, N.A., o cualquier otra tasa de referencia que Citibank, N.A. cotice en lugar de la Prime Rate, m&aacute;s 6 puntos porcentuales. Latino E-Learning se reserva el derecho de requerir previa aprobaci&oacute;n a los d&eacute;bitos en tarjetas de cr&eacute;dito o pago y/o la certificaci&oacute;n bancaria de cheques. Al menos que Ud. y Latino E-Learning hayan acordado de forma distinta alg&uacute;n descuento, la pol&iacute;tica est&aacute;ndar de precios de Latino E-Learning para Cursos marca Latino E-Learning que incluyen DVDs y servicios en un solo precio de descuento, distribuye el descuento del precio de lista aplicable a los servicios del sistema de forma equivalente y proporcional al porcentaje de descuento calculado del precio de lista para todo el sistema. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Entrega/T&iacute;tulo/Riesgo</strong>.&nbsp; La entrega se realizar&aacute; dentro del plazo indicado en la Confirmaci&oacute;n de Pedido y bajo la modalidad FCA<sup>1</sup>. Las entregas se pueden realizar por partes. El derecho de dominio se transfiere al Cliente al momento que Latino E-Learning entregue los Cursos a la empresa de transporte. Por el valor recibido, el Cliente le otorga a Latino E-Learning una prenda <em>(purchase money security interest)</em> sobre los Cursos hasta que el Precio total sea pagado; por lo tanto, el Cliente debe conservar los Cursos de Latino E-Learning por separado y no puede venderlos, gravarlos ni modificarlos hasta que haya pagado el Precio total. Latino E-Learning tiene derecho a ingresar en el local donde se guarda el Curso para retomar la posesi&oacute;n. Latino E-Learning tiene derecho a demandarlo por el Precio del Curso antes de la transmisi&oacute;n del dominio a un tercero. Si el Cliente rechaza la entrega sin previa aprobaci&oacute;n de Latino E-Learning, correr&aacute;n por su cuenta los gastos o da&ntilde;os resultantes, lo que incluye los gastos de almacenamiento hasta la aceptaci&oacute;n. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Aceptaci&oacute;n y devoluci&oacute;n.</strong>&nbsp; Ud. deber&aacute; examinar el Curso inmediatamente tras la entrega o dentro del plazo acordado con Latino E-Learning, si lo hubiere, para su inspecci&oacute;n o rechazo. Una vez transcurrido &eacute;ste, se considerar&aacute; que Ud. ha aceptado el Curso. Si Ud. tiene derecho a devolver un curso, requerimos que previamente nos contacte y obtenga autorizaci&oacute;n. Deber&aacute; devolver el Curso en sus condiciones originales, con su empaquetado, nota de devoluci&oacute;n y justificante de compra. Los costos de devoluci&oacute;n ser&aacute;n por su cuenta, salvo que exista una justificaci&oacute;n para la devoluci&oacute;n en t&eacute;rminos de la garant&iacute;a del Curso incluida en el paquete. Si la compra hubiera sido efectuada a distancia, por Internet, correo, venta telef&oacute;nica o por cat&aacute;logo Ud. tendr&aacute; derecho a la devoluci&oacute;n del curso sin necesidad de expresi&oacute;n de causa dentro de los 5 d&iacute;as posteriores a la entrega o en cualquier otra circunstancia de conformidad con los t&eacute;rminos y condiciones de devoluci&oacute;n en <span style="COLOR: #0000ff; TEXT-DECORATION: underline"><a href="http://www.latinoelearning.com/"><font color="#666666">www.latinoelearning.com</font></a></span>. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Garant&iacute;as</strong>.&nbsp; Las garant&iacute;as se incluyen en la P&oacute;liza de Garant&iacute;a que se entrega junto con el (los) Curso(s), y se regir&aacute; por lo establecido en ese documento, salvo por lo siguiente. Garantizamos que el Curso (excluyendo Cursos de Terceros) est&aacute; libre de defectos durante el t&eacute;rmino que se indique en el curso o alg&uacute;n otro documento que Latino E-Learning proporcione a Ud. Dicho plazo no podr&aacute; exceder en ning&uacute;n momento de 90 d&iacute;as naturales, desde su instalaci&oacute;n, para las piezas de recambio. Si el Curso fuese defectuoso durante este plazo, Latino E-Learning lo reparar&aacute; o sustituir&aacute;, a nuestra elecci&oacute;n, en un plazo razonable. Las reparaciones podr&aacute;n realizarse utilizando partes o cursos nuevos, equivalentes a nuevos o recondicionados que, aun cuando no sean id&eacute;nticos al Curso defectuoso, son equivalentes a nuevos en funcionalidad y aspecto. Ud. permitir&aacute; que Latino E-Learning examine, a nuestra elecci&oacute;n, el Curso en su ubicaci&oacute;n o locales de Latino E-Learning. Latino E-Learning es propietaria de las piezas reemplazadas y de los recambios y podr&aacute; cobrarlas al Cliente si este no las devuelve. Latino E-Learning prestar&aacute; la atenci&oacute;n necesaria para resolver los problemas en un plazo adecuado seg&uacute;n las circunstancias. </span><span style="FONT-SIZE: 12pt">Latino E-Learning no garantiza ni acepta responsabilidad por: </span>
    <ol type="1">
        <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Da&ntilde;os originados por instalaci&oacute;n incorrecta, uso, modificaci&oacute;n o reparaci&oacute;n realizada por tercero no debidamente autorizado o por Ud. mismo; </span></li>
        <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Da&ntilde;os causados por cualquier persona u otra fuerza externa; </span></li>
        <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Idoneidad del Curso para un fin, prop&oacute;sito o uso determinado; </span></li>
        <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Cursos de Terceros, Software y MI especificado por Ud., cuya garant&iacute;a Ud. recibir&aacute; directamente de su fabricante o licenciante; </span></li>
        <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Cualquier instrucci&oacute;n dada por Ud. y realizada por Latino E-Learning. </span></li>
        <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Que la operaci&oacute;n sea ininterrumpida y sin errores. La responsabilidad de Latino E-Learning por cualquier violaci&oacute;n a esta garant&iacute;a, a sus compromisos de servicios, o por cualquier otro concepto, en ning&uacute;n caso exceder&aacute; el Precio del Curso establecido en la Confirmaci&oacute;n del Pedido. Todos los cursos son proporcionados &quot;Como son&quot;. La garant&iacute;a de Latino E-Learning se otorga en lugar de todas las garant&iacute;as impl&iacute;citas y esas garant&iacute;as impl&iacute;citas est&aacute;n excluidas hasta el l&iacute;mite legalmente permitido. </span></li>
    </ol>
    </li>
</ol>
<div style="MARGIN: 0cm 0cm 10pt 36pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">LA GARANT&Iacute;A DESCRITA ES &Uacute;NICA Y EXCLUYENTE DE OTRAS GARANT&Iacute;AS, YA SEAN ESCRITAS U ORALES, EXPRESAS O T&Aacute;CITAS. LATINO E-LEARNING EXCLUYE EXPRESAMENTE A LAS GARANT&Iacute;AS T&Aacute;CITAS DE COMERCIALIDAD DEL PRODUCTO Y DE SU USO PARA UN PROP&Oacute;SITO DETERMINADO. </span></div>
<ol type="1" start="8">
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Servicios y Soporte</strong>. &nbsp; Los servicios, cuando se acuerde la prestaci&oacute;n de los mismos con el Cliente, ser&aacute;n prestados por Latino E-Learning o un Proveedor de Servicios y podr&aacute;n variar dependiendo del Curso. Los tiempos de respuesta son estimados y pueden variar seg&uacute;n el emplazamiento/ localizaci&oacute;n o accesibilidad al Curso. El servicio podr&aacute; proporcionarse v&iacute;a tel&eacute;fono o Internet cuando sea apropiado. Si est&aacute; convenido y se indic&oacute; en la Confirmaci&oacute;n del Pedido, la Oferta de Servicio puede incluir asesoramiento, etiquetado, instalaci&oacute;n, integraci&oacute;n, retirada, formaci&oacute;n y/o consulta. Salvo que estuviera expresamente previsto en la Confirmaci&oacute;n de Pedido, los Servicios no incluyen: art&iacute;culos excluidos de la garant&iacute;a, cambios en configuraci&oacute;n, recolocaci&oacute;n, mantenimiento preventivo, materiales consumibles, disquetes, CD's, trabajo que seg&uacute;n Latino E-Learning no sea necesario, entorno el&eacute;ctrico, transferencia de datos o Software, soluci&oacute;n a problemas causados por virus. Las reparaciones de Cursos de Terceros se efectuar&aacute;n seg&uacute;n la garant&iacute;a del fabricante o del licenciante. Piezas de recambio no cr&iacute;ticas para la funci&oacute;n del Curso (ej: bisagras, puertas, adornos, marcos) pueden no ser sustituidas en el plazo de la Oferta del Servicio. Latino E-Learning no estar&aacute; obligado a prestar el Servicio o Soporte hasta no en tanto Latino E-Learning haya recibido el pago en su totalidad. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Custom Factory Integration (CFI)</strong>.&nbsp; El Cliente podr&aacute; especificar y suministrar a Latino E-Learning el MI, o Latino E-Learning podr&aacute; obtenerlo siguiendo instrucciones. Latino E-Learning notificar&aacute; al Cliente la aceptaci&oacute;n y/o validaci&oacute;n del MI, e integrar&aacute; el MI en el Curso (produciendo un Curso CFI) que Latino E-Learning integrar&aacute; siguiendo las instrucciones que Ud. proporcione o el criterio t&eacute;cnico de Latino E-Learning, seg&uacute;n se acuerde. Latino E-Learning no integrar&aacute; CFI no operativo t&eacute;cnicamente desde nuestro punto de vista. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>L&iacute;mite de Responsabilidad.</strong>&nbsp; La responsabilidad de Latino E-Learning para con el Cliente respecto de los da&ntilde;os ocasionados o relacionados con el presente contrato, sin importar la forma de acci&oacute;n judicial o extrajudicial donde se determine una responsabilidad, ya sea contractual o extracontractual, por negligencia, dolo o mala fe o incumplimiento de garant&iacute;as, en todos los casos estar&aacute; limitada a y nunca podr&aacute; exceder de, en forma acumulada por todos los reclamos, acciones o causas de acci&oacute;n de cualquier tipo o naturaleza, el total de la contraprestaci&oacute;n pagada por el Cliente a Latino E-Learning por el pedido de que se trate, excluyendo impuestos y gastos. Ning&uacute;n reclamo, solicitud de mediaci&oacute;n o arbitraje o causa de acci&oacute;n derivada de un evento o eventos que hayan ocurrido en un t&eacute;rmino mayor a un a&ntilde;o a la fecha de la recepci&oacute;n de la demanda o solicitud de mediaci&oacute;n o arbitraje podr&aacute; ser utilizada o reclamada por cualquiera de las partes en contra de la otra. Latino E-Learning no responder&aacute; ni ser&aacute; responsable por: 1) p&eacute;rdida indirecta o consecuente; 2) p&eacute;rdida de negocio, salario, ingresos, ahorros; 3) da&ntilde;os remediados por Latino E-Learning dentro de un tiempo razonable; 4) p&eacute;rdida que hubiese podido ser evitable mediante una conducta razonable, incluyendo almacenamiento de datos en copias de seguridad y seguimiento de las recomendaciones de Latino E-Learning, en general; 5) art&iacute;culos excluidos de la garant&iacute;a o fuerza mayor. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Propiedad Intelectual</strong>.&nbsp; Latino E-Learning le indemnizar&aacute; por todos los costos y responsabilidades derivadas de reclamaciones por uso del Curso que viole cualquier derecho de propiedad intelectual o industrial de terceros. En ese caso, podremos ofrecerle, a nuestra sola opci&oacute;n, cambiarle o modificar el Curso o devolverle su Precio, menos su depreciaci&oacute;n. Ud. nos indemnizar&aacute; por responsabilidades derivadas del MI o propiedad intelectual o industrial cuya integraci&oacute;n hubiera sido requerida por Ud. o fueran de su propiedad, integrados en el Curso. Latino E-Learning se reserva el derecho a iniciar acci&oacute;n legal, transar y acordar la resoluci&oacute;n de las disputas, a su arbitrio, en caso de reclamaciones de un tercero basadas en derechos de propiedad intelectual. Ud. deber&aacute; asistirnos, a nuestro costo (excepto cuando la reclamaci&oacute;n derive de MI o propiedad intelectual o industrial cuya integraci&oacute;n hubiera sido requerida por Ud. o fueran de su propiedad, integrados en el Producto), cuando la disputa est&eacute; relacionada directamente con su Curso. Latino E-Learning reserva todos los derechos de propiedad intelectual e industrial que le correspondan sobre el Curso. Ud. notificar&aacute; a Latino E-Learning, inmediatamente, cualquier violaci&oacute;n o uso no autorizado del Curso o de su propiedad intelectual o industrial. La responsabilidad de Latino E-Learning en cualquier caso se limita al monto pagado por Ud. por el Curso. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Software</strong>. &nbsp; El cliente entiende y reconoce que el Curso se vende sin incluir el Software, siendo este &uacute;ltimo objeto de licencia concedida meramente al cliente para utilizarlo con el Curso. El Software que no sea propiedad de Latino E-Learning se suministra bajo licencia y garant&iacute;a de su licenciante. Latino E-Learning adjuntar&aacute; al Curso la licencia del Software que Ud. solicite, cuando sea necesario. Ud. se obliga a cumplir con los t&eacute;rminos de esa licencia. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Control de Exportaci&oacute;n</strong>. &nbsp; El Curso puede incluir tecnolog&iacute;a y Software sometidos a leyes sobre control de la exportaci&oacute;n de los EEUU, y del pa&iacute;s en el cual el Curso es entregado o usado, que deben ser respetadas por Ud. El Curso no se puede vender, arrendar o transferir a usuarios finales o pa&iacute;ses que se encuentren restringidos por dichas leyes o usuarios implicados en armamento de destrucci&oacute;n masiva o genocidio. Las restricciones de los EEUU var&iacute;an frecuentemente, dependiendo del Curso, por lo que Ud. deber&aacute; remitirse a las regulaciones vigentes en EEUU y en cada caso. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Caso Fortuito o Fuerza Mayor</strong>. &nbsp; No aceptamos responsabilidad por demoras (incluyendo entregas o servicios) causadas por circunstancias que escapen a nuestro control razonable y tendremos en tal caso derecho a una pr&oacute;rroga para su ejecuci&oacute;n; como ejemplo de estas circunstancias, pero sin car&aacute;cter limitativo, se incluyen huelgas, problemas de transporte, suministro o producci&oacute;n, fluctuaciones de tipos de cambio, acci&oacute;n gubernamental y desastres naturales. Si la causa durase m&aacute;s de 2 meses, este acuerdo podr&iacute;a ser resuelto por cualquier parte, sin derecho a compensaci&oacute;n. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Confidencialidad</strong>. &nbsp; Las partes deber&aacute;n tratar toda informaci&oacute;n recibida de la otra, que est&eacute; marcada como &quot;confidencial&quot; o que se pueda considerar razonablemente como confidencial, del mismo modo que tratar&iacute;an su propia informaci&oacute;n confidencial. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Resoluci&oacute;n</strong>. &nbsp; Latino E-Learning podr&aacute; rescindir este contrato previo aviso escrito si: 1) el Precio no es pagado puntualmente, a cuyo efecto las partes pactan expresamente que la falta de pago total o parcial producir&aacute; la rescisi&oacute;n del contrato de pleno derecho; 2) Ud. infringe o Latino E-Learning sospecha que Ud. ha infringido leyes sobre control a la exportaci&oacute;n. Cualquier parte puede resolver este contrato si la otra: 1) incumple de modo material y persistente este acuerdo y no remedia tal incumplimiento dentro de los 30 d&iacute;as siguiente a ser requerida por escrito al efecto; o 2) es declarada en suspensi&oacute;n de pagos, concurso mercantil, quiebra o no puede pagar sus deudas a la fecha del vencimiento. Latino E-Learning podr&aacute; optar por exigir la ejecuci&oacute;n de su obligaci&oacute;n de pagar el precio y en cualquier caso exigir resarcimiento de da&ntilde;os y perjuicios. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Obligaciones del Cliente</strong>. &nbsp; Ud. responder&aacute; por: </span>
    <ol type="1">
        <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Su propia elecci&oacute;n del Curso y su idoneidad para un fin o prop&oacute;sito; </span></li>
        <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Sus gastos de tel&eacute;fono y correo, en su caso, para contactar a Latino E-Learning; </span></li>
        <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Su especificaci&oacute;n en Cursos CFI e instrucciones dados por Ud.; </span></li>
        <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Todo MI, su funcionamiento, licencias y autorizaciones.</span> </li>
    </ol>
    </li>
</ol>
<div style="MARGIN: 0cm 0cm 10pt 36pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt">Ud. se dirigir&aacute; a nuestro personal con la suficiente cortes&iacute;a, y facilitar&aacute; informaci&oacute;n, cooperaci&oacute;n, colaboraci&oacute;n y acceso suficientes para permitir a Latino E-Learning cumplir con sus compromisos, de lo contrario quedaremos exentos de nuestras obligaciones. Ud. es responsable de la creaci&oacute;n de copias de seguridad y la confidencialidad de los datos contenidos en el Curso y el cumplimiento de cualquier otro requisito legal. </span></div>
<ol type="1" start="18">
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Protecci&oacute;n de los Datos</strong>. &nbsp; Sus datos ser&aacute;n tratados de acuerdo con las leyes de protecci&oacute;n de datos aplicables, a lo cual Ud. presta su consentimiento expreso. Ud. puede solicitarnos que no utilicemos sus datos para fines de marketing directo. Ud. podr&aacute; ejercitar sus derechos de acceso, rectificaci&oacute;n y cancelaci&oacute;n mediante comunicaci&oacute;n escrita a la direcci&oacute;n de Latino E-Learning. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Derechos de los Consumidores</strong>. &nbsp; Si Ud. es un Consumidor, ninguna disposici&oacute;n en este contrato afectar&aacute; en modo alguno las disposiciones de orden p&uacute;blico en materia de derechos de los consumidores. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Jurisdicci&oacute;n</strong>. &nbsp; Este contrato se considera celebrado en la ciudad de Guayaquil, provincia de Guayas, Ecuador, y se rige por las leyes de ese estado, sin perjuicio de la legislaci&oacute;n en materia de conflicto de leyes; asimismo, las partes se someten a la jurisdicci&oacute;n exclusiva de los tribunales estatales y federales de la provincia del Guayas. Queda convenido entre las partes que no se aplicar&aacute;n al presente las disposiciones del convenio de Viena sobre los contratos para la compra-venta internacional de mercader&iacute;as. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Encabezados</strong>. &nbsp; Los encabezados de cada uno de los puntos son para referencia y conveniencia y no forman parte de los T&eacute;rminos y Condiciones de Venta. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt"><strong>Varios</strong>. &nbsp; Si cualquier disposici&oacute;n en este contrato fuese declarada inv&aacute;lida o inaplicable por un Tribunal el resto de las mismas no se ver&aacute; afectado. Latino E-Learning puede subcontratar sus obligaciones a terceros sin necesidad de aprobaci&oacute;n de su parte. Ninguna de las partes puede ceder o transferir cualesquiera obligaciones o derechos. Las notificaciones deben hacerse por escrito (a mano, por e-mail, fax o correo certificado) y enviadas al representante legal de la otra parte. </span></li>
    <li style="MARGIN: 0cm 0cm 10pt; LINE-HEIGHT: normal"><span style="FONT-SIZE: 12pt; LINE-HEIGHT: 115%"><strong>Informaci&oacute;n</strong>. &nbsp; Ud. encontrar&aacute; informaci&oacute;n relativa a Latino E-Learning y sus procedimientos en la p&aacute;gina web </span><span style="FONT-SIZE: 11pt; LINE-HEIGHT: 115%"><a href="http://www1.la.dell.com/content/default.aspx?c=ec&amp;l=es&amp;s=gen"><span style="FONT-SIZE: 12pt; COLOR: #0000ff; LINE-HEIGHT: 115%; TEXT-DECORATION: underline">www.latinoelearning.com</span></a></span><span style="FONT-SIZE: 12pt; LINE-HEIGHT: 115%">. Puede dirigirse a esa p&aacute;gina para conocer cualquier actualizaci&oacute;n.</span> </li>
</ol>
