//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace Commerce.Providers.StrikeIron {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'validation' from namespace 'http://www.strikeiron.com' was not handled.
    // CODEGEN: The optional WSDL extension element 'validation' from namespace 'http://www.strikeiron.com' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TaxDataBasicSoap", Namespace="http://www.strikeiron.com")]
    public partial class TaxDataBasic : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private LicenseInfo licenseInfoValueField;
        
        private ResponseInfo responseInfoValueField;
        
        private SubscriptionInfo subscriptionInfoValueField;
        
        private System.Threading.SendOrPostCallback GetTaxRateUSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTaxRateCanadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRemainingHitsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TaxDataBasic() {
            this.Url = global::Commerce.Providers.Properties.Settings.Default.Commerce_TaxProvider_StrikeIron_TaxDataBasic;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public LicenseInfo LicenseInfoValue {
            get {
                return this.licenseInfoValueField;
            }
            set {
                this.licenseInfoValueField = value;
            }
        }
        
        public ResponseInfo ResponseInfoValue {
            get {
                return this.responseInfoValueField;
            }
            set {
                this.responseInfoValueField = value;
            }
        }
        
        public SubscriptionInfo SubscriptionInfoValue {
            get {
                return this.subscriptionInfoValueField;
            }
            set {
                this.subscriptionInfoValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTaxRateUSCompletedEventHandler GetTaxRateUSCompleted;
        
        /// <remarks/>
        public event GetTaxRateCanadaCompletedEventHandler GetTaxRateCanadaCompleted;
        
        /// <remarks/>
        public event GetRemainingHitsCompletedEventHandler GetRemainingHitsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("LicenseInfoValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SubscriptionInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.strikeiron.com/GetTaxRateUS", RequestNamespace="http://www.strikeiron.com", ResponseNamespace="http://www.strikeiron.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaxRateUSAData GetTaxRateUS(string zip_code) {
            object[] results = this.Invoke("GetTaxRateUS", new object[] {
                        zip_code});
            return ((TaxRateUSAData)(results[0]));
        }
        
        /// <remarks/>
        public void GetTaxRateUSAsync(string zip_code) {
            this.GetTaxRateUSAsync(zip_code, null);
        }
        
        /// <remarks/>
        public void GetTaxRateUSAsync(string zip_code, object userState) {
            if ((this.GetTaxRateUSOperationCompleted == null)) {
                this.GetTaxRateUSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTaxRateUSOperationCompleted);
            }
            this.InvokeAsync("GetTaxRateUS", new object[] {
                        zip_code}, this.GetTaxRateUSOperationCompleted, userState);
        }
        
        private void OnGetTaxRateUSOperationCompleted(object arg) {
            if ((this.GetTaxRateUSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTaxRateUSCompleted(this, new GetTaxRateUSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("LicenseInfoValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SubscriptionInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.strikeiron.com/GetTaxRateCanada", RequestNamespace="http://www.strikeiron.com", ResponseNamespace="http://www.strikeiron.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaxRateCanadaData GetTaxRateCanada(string province) {
            object[] results = this.Invoke("GetTaxRateCanada", new object[] {
                        province});
            return ((TaxRateCanadaData)(results[0]));
        }
        
        /// <remarks/>
        public void GetTaxRateCanadaAsync(string province) {
            this.GetTaxRateCanadaAsync(province, null);
        }
        
        /// <remarks/>
        public void GetTaxRateCanadaAsync(string province, object userState) {
            if ((this.GetTaxRateCanadaOperationCompleted == null)) {
                this.GetTaxRateCanadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTaxRateCanadaOperationCompleted);
            }
            this.InvokeAsync("GetTaxRateCanada", new object[] {
                        province}, this.GetTaxRateCanadaOperationCompleted, userState);
        }
        
        private void OnGetTaxRateCanadaOperationCompleted(object arg) {
            if ((this.GetTaxRateCanadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTaxRateCanadaCompleted(this, new GetTaxRateCanadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LicenseInfoValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SubscriptionInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.strikeiron.com/StrikeIron/taxdatabasic/TaxDataBasic/GetRemainingHits", RequestNamespace="http://ws.strikeiron.com", ResponseNamespace="http://ws.strikeiron.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetRemainingHits() {
            this.Invoke("GetRemainingHits", new object[0]);
        }
        
        /// <remarks/>
        public void GetRemainingHitsAsync() {
            this.GetRemainingHitsAsync(null);
        }
        
        /// <remarks/>
        public void GetRemainingHitsAsync(object userState) {
            if ((this.GetRemainingHitsOperationCompleted == null)) {
                this.GetRemainingHitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRemainingHitsOperationCompleted);
            }
            this.InvokeAsync("GetRemainingHits", new object[0], this.GetRemainingHitsOperationCompleted, userState);
        }
        
        private void OnGetRemainingHitsOperationCompleted(object arg) {
            if ((this.GetRemainingHitsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRemainingHitsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.strikeiron.com", IsNullable=false)]
    public partial class ResponseInfo : System.Web.Services.Protocols.SoapHeader {
        
        private int responseCodeField;
        
        private string responseField;
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class TaxRateCanadaData {
        
        private string abbreviationField;
        
        private string provinceField;
        
        private double gSTField;
        
        private double pSTField;
        
        private double totalField;
        
        private string hSTField;
        
        /// <remarks/>
        public string abbreviation {
            get {
                return this.abbreviationField;
            }
            set {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        public double GST {
            get {
                return this.gSTField;
            }
            set {
                this.gSTField = value;
            }
        }
        
        /// <remarks/>
        public double PST {
            get {
                return this.pSTField;
            }
            set {
                this.pSTField = value;
            }
        }
        
        /// <remarks/>
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string HST {
            get {
                return this.hSTField;
            }
            set {
                this.hSTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.strikeiron.com")]
    public partial class TaxRateUSAData {
        
        private string zip_codeField;
        
        private string stateField;
        
        private string county_nameField;
        
        private string city_nameField;
        
        private double state_sales_taxField;
        
        private double state_use_taxField;
        
        private double county_sales_taxField;
        
        private double county_use_taxField;
        
        private double city_sales_taxField;
        
        private double city_use_taxField;
        
        private double total_sales_taxField;
        
        private double total_use_taxField;
        
        private string tax_shipping_aloneField;
        
        private string tax_shipping_handlingField;
        
        /// <remarks/>
        public string zip_code {
            get {
                return this.zip_codeField;
            }
            set {
                this.zip_codeField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string county_name {
            get {
                return this.county_nameField;
            }
            set {
                this.county_nameField = value;
            }
        }
        
        /// <remarks/>
        public string city_name {
            get {
                return this.city_nameField;
            }
            set {
                this.city_nameField = value;
            }
        }
        
        /// <remarks/>
        public double state_sales_tax {
            get {
                return this.state_sales_taxField;
            }
            set {
                this.state_sales_taxField = value;
            }
        }
        
        /// <remarks/>
        public double state_use_tax {
            get {
                return this.state_use_taxField;
            }
            set {
                this.state_use_taxField = value;
            }
        }
        
        /// <remarks/>
        public double county_sales_tax {
            get {
                return this.county_sales_taxField;
            }
            set {
                this.county_sales_taxField = value;
            }
        }
        
        /// <remarks/>
        public double county_use_tax {
            get {
                return this.county_use_taxField;
            }
            set {
                this.county_use_taxField = value;
            }
        }
        
        /// <remarks/>
        public double city_sales_tax {
            get {
                return this.city_sales_taxField;
            }
            set {
                this.city_sales_taxField = value;
            }
        }
        
        /// <remarks/>
        public double city_use_tax {
            get {
                return this.city_use_taxField;
            }
            set {
                this.city_use_taxField = value;
            }
        }
        
        /// <remarks/>
        public double total_sales_tax {
            get {
                return this.total_sales_taxField;
            }
            set {
                this.total_sales_taxField = value;
            }
        }
        
        /// <remarks/>
        public double total_use_tax {
            get {
                return this.total_use_taxField;
            }
            set {
                this.total_use_taxField = value;
            }
        }
        
        /// <remarks/>
        public string tax_shipping_alone {
            get {
                return this.tax_shipping_aloneField;
            }
            set {
                this.tax_shipping_aloneField = value;
            }
        }
        
        /// <remarks/>
        public string tax_shipping_handling {
            get {
                return this.tax_shipping_handlingField;
            }
            set {
                this.tax_shipping_handlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.strikeiron.com")]
    public partial class RegisteredUser {
        
        private string userIDField;
        
        private string passwordField;
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.strikeiron.com")]
    public partial class UnregisteredUser {
        
        private string emailAddressField;
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.strikeiron.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.strikeiron.com", IsNullable=false)]
    public partial class LicenseInfo : System.Web.Services.Protocols.SoapHeader {
        
        private UnregisteredUser unregisteredUserField;
        
        private RegisteredUser registeredUserField;
        
        /// <remarks/>
        public UnregisteredUser UnregisteredUser {
            get {
                return this.unregisteredUserField;
            }
            set {
                this.unregisteredUserField = value;
            }
        }
        
        /// <remarks/>
        public RegisteredUser RegisteredUser {
            get {
                return this.registeredUserField;
            }
            set {
                this.registeredUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.strikeiron.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ws.strikeiron.com", IsNullable=false)]
    public partial class SubscriptionInfo : System.Web.Services.Protocols.SoapHeader {
        
        private int licenseStatusCodeField;
        
        private string licenseStatusField;
        
        private int licenseActionCodeField;
        
        private string licenseActionField;
        
        private int remainingHitsField;
        
        private decimal amountField;
        
        /// <remarks/>
        public int LicenseStatusCode {
            get {
                return this.licenseStatusCodeField;
            }
            set {
                this.licenseStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseStatus {
            get {
                return this.licenseStatusField;
            }
            set {
                this.licenseStatusField = value;
            }
        }
        
        /// <remarks/>
        public int LicenseActionCode {
            get {
                return this.licenseActionCodeField;
            }
            set {
                this.licenseActionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseAction {
            get {
                return this.licenseActionField;
            }
            set {
                this.licenseActionField = value;
            }
        }
        
        /// <remarks/>
        public int RemainingHits {
            get {
                return this.remainingHitsField;
            }
            set {
                this.remainingHitsField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetTaxRateUSCompletedEventHandler(object sender, GetTaxRateUSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTaxRateUSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTaxRateUSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaxRateUSAData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaxRateUSAData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetTaxRateCanadaCompletedEventHandler(object sender, GetTaxRateCanadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTaxRateCanadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTaxRateCanadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaxRateCanadaData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaxRateCanadaData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetRemainingHitsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591